version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-meetings
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq-meetings
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    container_name: meetings-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Meetings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d Meetings" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meetings-net

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: meetings-pgadmin
      restart: unless-stopped
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      ports:
        - "5050:80"
      volumes:
        - pgadmin_data:/var/lib/pgadmin
      depends_on:
        postgres:
          condition: service_healthy
      networks:
        - meetings-net

volumes:
  redis-data:
  postgres_data:
  pgadmin_data:

networks:
  meetings-net:
    driver: bridge